# Generated by Django 5.2 on 2025-05-19 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymvault', '0002_gym_user_address_user_phone_gymadmin_member_locker_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='member',
            name='start_date',
        ),
    ]
