# Generated by Django 5.2 on 2025-05-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymvault', '0003_remove_member_end_date_remove_member_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='member',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
